### ISSUE TITLE
There was a problem uploading this file.

### ISSUE THREAD

**Issue by playground** [adamhenson/s3-image-uploader#2]
Is there a way to get better error message?  All I'm getting is "There was a problem uploading this file".

**Comment by adamhenson** [comment]
Thanks @playground - I agree. You must be seeing this message in the `errorCallback` of `Uploader.upload`.

Originally, I don't think I wanted to expose server information, so I created a generic message. However, I think details are necessary here.

Therefore I provided an additional parameter to `errorCallback`. I updated the README, but here's an example of how one could use it:

``` javascript
uploader.upload({
  fileId : 'someUniqueIdentifier',
  bucket : 'somebucket',
  source : './public/tmp/myoldimage.jpg',
  name : 'mynewimage.jpg'
},
function(data){ // success
  console.log('upload success:', data);
  // execute success code
},
function(errMsg, errObject){ //error
  console.error('unable to upload: ' + errMsg + ':', errObject);
  // execute error code
});
```

You'll need to re-install this module to test. I've updated in NPM.

**Comment by playground** [comment]
Thanks @adamhenson for the quick response.  That error message comes in handy :-).
I was able to upload the image to s3 bucket.

**Comment by adamhenson** [comment]
Excellent, glad this helped @playground. Thanks for calling it out.

**Comment by doublesharp** [comment]
This makes it more difficult to use Promises unfortunately. 

I realize this would be a breaking change, but using the pattern `uploader.upload(options, callback(err, data))` would allow the modules to be `promisified` via [`es6-promisify`](https://www.npmjs.com/package/es6-promisify). 

On success you would `return callback(null, data)` and on error you would `return(err, null)` which would translate to 

```
const promisify = require('es6-promisify');

promisify(uploader.upload)(options)
.then(data => console.log(data))
.catch(err => console.log(err));
```

**Comment by adamhenson** [comment]
@doublesharp - I'm not familiar with `es6-promisify`, and I'm not sure if I follow your point. `errObject` is an optional argument. I believe your example above would not be affected by this change.

In `.catch(err => console.log(err));` - wouldn't `err` represent `errMsg` from my example above?

**Comment by doublesharp** [comment]
I was referring to "node style callbacks" or "error first".

http://thenodeway.io/posts/understanding-error-first-callbacks/

**Comment by adamhenson** [comment]
Right, @doublesharp. I really haven't given this project much attention for some time. It could use some refactoring to support promises.

Your concerns are valid, but irrelevant to this issue. It's more relevant to this project as a whole, as the issue you describe existed before this one (#2).

Feel free to submit your issue... or even better a PR to address your concerns.

**Comment by doublesharp** [comment]
It would definitely affect the project as a whole, so it would probably be more appropriate for a major version update if you did it at all - no pressure at all. I was looking into error handling which is why I thought this was an appropriate place to comment. I'll certainly submit a PR if I make any updates. Thanks!

**Comment by adamhenson** [comment]
Certainly, your comments are welcome. Thanks @doublesharp. Hopefully sometime soon I can give this project more love.
